### PR TITLE
Add tests and fix bugs

### PR DESCRIPTION
**Pull request by txus**
Hi! Thank you for this, first of all! I fixed a few bugs and added tests, both for synchronous and async usage, and also for Redis specifically.

### CODE REVIEW

**Comment by shobrook** [comment]
Hey, thanks for opening this! I'm a bit busy this week but I'll take a look as soon as I can.

**Comment by justinphan3110cais** [comment]
I got `'NoneType' object has no attribute 'wait_for_capacity_sync'`
error on this pull

**Comment by gingerwizard** [comment]
I'm getting `local variable 'redis' referenced before assignment` without this, any chance we could get this merged?


```
ERROR - local variable 'redis' referenced before assignment
Traceback (most recent call last):
  File "/opt/udfs/sentiment_distributed.py", line 34, in extract_sentiment
    with rate_limiter.limit(**params):
  File "/opt/udfs/.venv/lib/python3.9/site-packages/openlimit/utilities/context_decorators.py", line 47, in __enter__
    asyncio.run(self.rate_limiter.wait_for_capacity(self.num_tokens))
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/udfs/.venv/lib/python3.9/site-packages/openlimit/redis_rate_limiters.py", line 54, in wait_for_capacity
    await self._init_buckets()
  File "/opt/udfs/.venv/lib/python3.9/site-packages/openlimit/redis_rate_limiters.py", line 40, in _init_buckets
    redis = await redis.asyncio.from_url(self._redis_url, encoding="utf-8", decode_responses=True)
UnboundLocalError: local variable 'redis' referenced before assignment
```

**Comment by gingerwizard** [comment]
@shobrook we'd like to use this in a blog post for ClickHouse.com if you have any interest in addressing..

**Comment by shobrook** [comment]
Hi, sorry for the delay. Taking a look now.

**Comment by shobrook** [comment]
Merged. Also upgraded the package on PyPi (`v0.3.0`). Please let me know if it's working for you now @gingerwizard. And thank you for offering to mention this in your blog post!

**Comment by gingerwizard** [comment]
thanks @shobrook same issue https://github.com/shobrook/openlimit/issues/9 'NoneType' object has no attribute 'wait_for_capacity_sync'

**Pull request merged**
