### PR TITLE
Update redis dep and implement wait_for_capacity_sync

### PR DESCRIPTION
**Pull request by trustalex**
- Use latest redis version since aioredis is depreciated
- Add simple implementation of wait_for_capacity_sync to use async and wait

### CODE REVIEW

**Comment by ctjlewis** [comment]
@shobrook Hate to ping, would it be possible to get a review on this? Blocking for us and a few others.

Love this library though, use it in all my Colab notebooks.

**Comment by ArthurCockfield** [comment]
Is this fixed? having this exact error on Python 3.12.3 at the moment

**Comment by npip99** [comment]
If anyone else is running into this error, you can pip install `git+https://github.com/shobrook/openlimit.git@ae77eb7d41f537ce1e68f78031f4b7197ddf29f4#egg=openlimit` , which also works in requirements.in and requirements.txt

**Comment by npip99** [comment]
@shobrook Do you know the status on redeploying this to pypi? pypi is still using an old version (0.3.0)

**Pull request merged**
